### ISSUE TITLE
Unable to get hello world example to work

### ISSUE THREAD

**Issue by c4milo** [GoogleCloudPlatform/cloud-bigtable-examples#153] opened 2016-04-04 22:12 UTC
This is what I'm currently getting when using in a self-contained jar:

```
$ java -jar dist/job-driver.jar personalization_test_bigtable_client
arg:[0]	personalization_test_bigtable_client
16/04/04 18:05:42 INFO grpc.BigtableSession: Opening connection for projectId project-id, zoneId us-central1-c, clusterId myclusterid, on data host bigtable.googleapis.com, table admin host bigtabletableadmin.googleapis.com.
16/04/04 18:05:42 INFO grpc.BigtableSession: gRPC is using the OpenSSL provider (tcnactive jar - Open Ssl version: BoringSSL)
16/04/04 18:05:42 INFO io.RefreshingOAuth2CredentialsInterceptor: Refreshing the OAuth token
java.lang.IllegalStateException: Could not find an apporpriate constructor for com.google.cloud.bigtable.hbase1_1.BigtableConnection
	at com.google.cloud.bigtable.hbase.BigtableConfiguration.connect(BigtableConfiguration.java:65)
	at com.google.cloud.bigtable.hbase.BigtableConfiguration.connect(BigtableConfiguration.java:55)
	at com.nytimes.cig.PersonalizationTestBigTableClientModule.doHelloWorld(PersonalizationTestBigTableClientModule.java:60)
	at com.nytimes.cig.PersonalizationTestBigTableClientModule.main(PersonalizationTestBigTableClientModule.java:128)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.nytimes.cig.ProgramDriver$ProgramDescription.invoke(ProgramDriver.java:68)
	at com.nytimes.cig.ProgramDriver.driver(ProgramDriver.java:139)
	at com.nytimes.cig.JobDriver.main(JobDriver.java:83)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at com.google.cloud.bigtable.hbase.BigtableConfiguration.connect(BigtableConfiguration.java:62)
	... 10 more
Caused by: java.lang.NoSuchFieldError: METHOD_SAMPLE_ROW_KEYS
	at com.google.cloud.bigtable.grpc.async.BigtableAsyncUtilities$Default.createSampleRowKeyAsyncReader(BigtableAsyncUtilities.java:111)
	at com.google.cloud.bigtable.grpc.BigtableDataGrpcClient.<init>(BigtableDataGrpcClient.java:168)
	at com.google.cloud.bigtable.grpc.BigtableDataGrpcClient.<init>(BigtableDataGrpcClient.java:152)
	at com.google.cloud.bigtable.grpc.BigtableSession.<init>(BigtableSession.java:256)
	at org.apache.hadoop.hbase.client.AbstractBigtableConnection.<init>(AbstractBigtableConnection.java:137)
	at org.apache.hadoop.hbase.client.AbstractBigtableConnection.<init>(AbstractBigtableConnection.java:105)
	at com.google.cloud.bigtable.hbase1_1.BigtableConnection.<init>(BigtableConnection.java:37)
	... 15 more
```

**Comment by sduskis** [comment] 2016-04-04 23:40
It's not clear to me why this would happen.  Would you be able to give more information about the contents of job-driver.jar?  That's probably the key to this mystery.

**Comment by sduskis** [comment] 2016-04-05 14:22
@c4milo: This problem doesn't seem to be with any of our code.  We need more information about what's in job-driver.jar in order to help.  I'm going to close this issue for now, since we cannot reproduce this problem without more information from you.

**Closed by sduskis** 2016-04-05 14:22 UTC

**Comment by c4milo** [comment] 2016-04-05 15:12
@sduskis fair enough, I will review more closely as job-driver does indeed have lots of jars embedded. Thanks and apologies for the noise!

**Comment by shouguolisc** [comment] 2016-05-11 04:34
hmm i'm seeing this error as well...

@sduskis: do you have a hello-world project for grpc client? I think that might help ppl down the road.

**Comment by c4milo** [comment] 2016-05-11 16:16
FWIW @shouguolisc, taking bigtable-protos.jar out of my classpath fixed it for me.
